services:
  docs:
    image: only_django_local_docs
    container_name: only_django_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./only_django:/app/only_django:z
    ports:
      - '9000:9000'
    command: /start-docs
